name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      enable_coverage:
        description: 'Enable coverage?'
        type: boolean
        required: true
        default: 'true'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Cache the Git repository folder
        uses: actions/cache@v3
        with:
          path: ./.git
          key: git-folder
      - name: Checkout Gadgets (recursively)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

  build-and-test-with-coverage:
    runs-on: ubuntu-latest
    needs:
      - checkout
    if: ${{ inputs.enable_coverage == true }}
    steps:
      - name: Configure Gadgets (with coverage)
        run: |
          mkdir build && cd build
          cmake -DGADGETS_WITH_COVERAGE=ON ..
      - name: Build Gadgets
        run: |
          cd build
          make -j`nproc`
      - name: Run Tests (with coverage)
        run: |
          sudo apt-get -y install lcov
          tools/coverage.sh

build-and-test-only:
    runs-on: ubuntu-latest
    needs:
      - checkout
    if: ${{ inputs.enable_coverage != true }}
    steps:
      name: Configure Gadgets
        run: |
          mkdir build && cd build
          cmake ..
      - name: Build Gadgets
        run: |
          cd build
          make -j`nproc`
      - name: Run Tests
        run: |
          cd build-gcc/src/TestRunner
          ./GadgetsTestRunner
