name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test-linux-gcc:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache the Git repository folder
        uses: actions/cache@v4
        with:
          path: ./.git
          key: git-folder

      - name: Checkout Gadgets (recursively)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Gadgets
        run: |
          mkdir build-gcc && cd build-gcc
          cmake -DGADGETS_WITH_COVERAGE=ON ..

      - name: Build Gadgets
        run: |
          tools/build.sh

      - name: Run Tests
        run: |
          sudo apt-get -y install lcov
          tools/coverage.sh

  build-and-test-linux-clang:
    runs-on: ubuntu-22.04
    steps:
      - name: Cache the Git repository folder
        uses: actions/cache@v4
        with:
          path: ./.git
          key: git-folder

      # newer version of clang is required due to issues with included version in the
      # image - install v17.0.x and use clang-17/clang++-17 during project configuration
      - name: Install newer Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17

      - name: Checkout Gadgets (recursively)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Gadgets
        run: |
          mkdir build-clang && cd build-clang
          cmake -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17 ..

      - name: Build Gadgets
        run: |
          cd build-clang
          make -j`nproc`

      - name: Run Tests
        run: |
          cd build-clang/src/Tests
          ./GadgetsTestRunner
