name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_call:
    inputs:
      enable_coverage:
        type: boolean
        required: true
        default: true
  workflow_dispatch:
    inputs:
      enable_coverage:
        description: 'Enable coverage?'
        type: boolean
        required: true
        default: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache the Git repository folder
        uses: actions/cache@v3
        with:
          path: ./.git
          key: git-folder

      - name: Checkout Gadgets (recursively)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure Gadgets
        if: ${{ inputs.enable_coverage == false }}
        run: |
          mkdir build-gcc && cd build-gcc
          cmake ..

      - name: Configure Gadgets (with coverage)
        if: ${{ inputs.enable_coverage == true }}
        run: |
          mkdir build-gcc && cd build-gcc
          cmake -DGADGETS_WITH_COVERAGE=ON ..

      - name: Build Gadgets
        run: |
          cd build-gcc
          make -j`nproc`

      - name: Run Tests
        if: ${{ inputs.enable_coverage == false }}
        run: |
          cd build-gcc/src/TestRunner
          ./GadgetsTestRunner

      - name: Run Tests (with coverage)
        if: ${{ inputs.enable_coverage == true }}
        run: |
          sudo apt-get -y install lcov
          tools/coverage.sh
